name: jinhe
description: 金河市公交线路系统

# Prevent the package from being accidentally published to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-262.0.dev"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  dependency_validator:
  msix:

flutter:
  uses-material-design: true
