name: jinhe
description: 金河市公交线路系统

# Prevent the package from being accidentally published to pub.dev.
publish_to: "none"

version: 0.2.0+2

environment:
  sdk: ">=2.15.0-262.0.dev"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  dependency_validator:
  msix:

msix_config:
  display_name: "金河市公交线路系统"
  publisher_display_name: "CCXXXI"
  identity_name: "io.github.ccxxxi.jinhe"
  msix_version: 0.2.0.2
  logo_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
