name: build

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    working-directory: jinhe

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe

      - run: flutter build web

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: jinhe/build/web

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe

      - run: flutter build windows

      - uses: papeloto/action-zip@v1
        with:
          files: jinhe/build/windows/runner/Release/
          dest: windows-release.zip
      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: windows-release.zip

      - run: flutter pub run msix:create

      - uses: actions/upload-artifact@v2
        with:
          name: msix
          path: jinhe/build/windows/runner/Release/jinhe.msix

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe
      - run: sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev

      - run: flutter build linux

      - uses: papeloto/action-zip@v1
        with:
          files: jinhe/build/linux/x64/release/bundle/
          dest: linux-release.zip
      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: linux-release.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe

      - run: flutter build macos

      - uses: papeloto/action-zip@v1
        with:
          files: jinhe/build/macos/Build/Products/Release/
          dest: macos-release.zip
      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: macos-release.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe
      - run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/app/key.jks
      - run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - run: flutter build apk --split-per-abi

      - uses: actions/upload-artifact@v2
        with:
          name: android
          path: jinhe/build/app/outputs/apk/release/*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe

      - run: flutter build ios --no-codesign

      - uses: papeloto/action-zip@v1
        with:
          files: jinhe/build/ios/Release-iphoneos/Runner.app/
          dest: ios-release.zip
      - uses: actions/upload-artifact@v2
        with:
          name: ios
          path: ios-release.zip

  release:
    needs: [ build-windows, build-linux, build-macos, build-android, build-ios ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            **/*.zip
            **/*.msix
            **/*.apk
