name: build-test

on:
  push:
    branches:
      - "dev"

defaults:
  run:
    working-directory: jinhe_client

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe_client

      - run: flutter build web

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: jinhe_client/build/web/
          publish_branch: gh-pages-alter

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe_client
      - run: sudo apt-get update && sudo apt-get -y install clang cmake ninja-build pkg-config libgtk-3-dev

      - run: flutter build linux
