name: check

on:
  push:
  pull_request:
  schedule:
    - cron: '10 17 * * FRI'

defaults:
  run:
    working-directory: jinhe

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe
      - run: flutter analyze

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v2

  dependency_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: CCXXXI/flutter-action@main
        with:
          directory: jinhe
      - run: flutter pub run dependency_validator
